services:
  fuseki:
    image: stain/jena-fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=pw
      - FUSEKI_DATASET_1=imr
      - TDB=2
    volumes:
      - ./ontology:/staging
      - fuseki_data:/fuseki

volumes:
  fuseki_data:
    driver: local
